// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spacestation.proto

package proto;

public interface CaptainOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Captain)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *&#47;////////////////////enum//////////////////////
   * </pre>
   *
   * <code>optional .proto.Captain.RaceType race = 2;</code>
   */
  boolean hasRace();
  /**
   * <pre>
   *&#47;////////////////////enum//////////////////////
   * </pre>
   *
   * <code>optional .proto.Captain.RaceType race = 2;</code>
   */
  proto.Captain.RaceType getRace();
}
