// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spacestation.proto

package proto;

public final class SpaceStationOuter {
  private SpaceStationOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Captain_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Captain_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SpaceShip_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SpaceShip_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SpaceStation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SpaceStation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022spacestation.proto\022\005proto\"n\n\007Captain\022\014" +
      "\n\004name\030\001 \002(\t\022%\n\004race\030\002 \001(\0162\027.proto.Capta" +
      "in.RaceType\".\n\010RaceType\022\t\n\005FURRY\020\000\022\n\n\006VU" +
      "LCAN\020\001\022\013\n\007KLINGON\020\002\"6\n\tSpaceShip\022\014\n\004name" +
      "\030\001 \002(\t\022\014\n\004crew\030\002 \001(\005\022\r\n\005cargo\030\003 \001(\t\"j\n\014S" +
      "paceStation\022\023\n\013designation\030\001 \002(\t\022\037\n\007capt" +
      "ain\030\002 \002(\0132\016.proto.Captain\022$\n\nspaceships\030" +
      "\003 \003(\0132\020.proto.SpaceShipB\025B\021SpaceStationO" +
      "uterP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Captain_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Captain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Captain_descriptor,
        new java.lang.String[] { "Name", "Race", });
    internal_static_proto_SpaceShip_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_SpaceShip_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SpaceShip_descriptor,
        new java.lang.String[] { "Name", "Crew", "Cargo", });
    internal_static_proto_SpaceStation_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_SpaceStation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SpaceStation_descriptor,
        new java.lang.String[] { "Designation", "Captain", "Spaceships", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
