// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spacestation.proto

package proto;

public interface SpaceShipOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.SpaceShip)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 crew = 2;</code>
   */
  boolean hasCrew();
  /**
   * <code>optional int32 crew = 2;</code>
   */
  int getCrew();

  /**
   * <code>optional string cargo = 3;</code>
   */
  boolean hasCargo();
  /**
   * <code>optional string cargo = 3;</code>
   */
  java.lang.String getCargo();
  /**
   * <code>optional string cargo = 3;</code>
   */
  com.google.protobuf.ByteString
      getCargoBytes();
}
