// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package studentsClasses;

/**
 * Protobuf type {@code studentsClasses.Classroom}
 */
public  final class Classroom extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:studentsClasses.Classroom)
    ClassroomOrBuilder {
  // Use Classroom.newBuilder() to construct.
  private Classroom(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Classroom() {
    prof_ = "";
    student_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Classroom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            prof_ = bs;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              student_ = new java.util.ArrayList<studentsClasses.Student>();
              mutable_bitField0_ |= 0x00000002;
            }
            student_.add(
                input.readMessage(studentsClasses.Student.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        student_ = java.util.Collections.unmodifiableList(student_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return studentsClasses.StudentOuterClass.internal_static_studentsClasses_Classroom_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return studentsClasses.StudentOuterClass.internal_static_studentsClasses_Classroom_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            studentsClasses.Classroom.class, studentsClasses.Classroom.Builder.class);
  }

  private int bitField0_;
  public static final int PROF_FIELD_NUMBER = 1;
  private volatile java.lang.Object prof_;
  /**
   * <code>required string prof = 1;</code>
   */
  public boolean hasProf() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string prof = 1;</code>
   */
  public java.lang.String getProf() {
    java.lang.Object ref = prof_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        prof_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string prof = 1;</code>
   */
  public com.google.protobuf.ByteString
      getProfBytes() {
    java.lang.Object ref = prof_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      prof_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STUDENT_FIELD_NUMBER = 2;
  private java.util.List<studentsClasses.Student> student_;
  /**
   * <code>repeated .studentsClasses.Student student = 2;</code>
   */
  public java.util.List<studentsClasses.Student> getStudentList() {
    return student_;
  }
  /**
   * <code>repeated .studentsClasses.Student student = 2;</code>
   */
  public java.util.List<? extends studentsClasses.StudentOrBuilder> 
      getStudentOrBuilderList() {
    return student_;
  }
  /**
   * <code>repeated .studentsClasses.Student student = 2;</code>
   */
  public int getStudentCount() {
    return student_.size();
  }
  /**
   * <code>repeated .studentsClasses.Student student = 2;</code>
   */
  public studentsClasses.Student getStudent(int index) {
    return student_.get(index);
  }
  /**
   * <code>repeated .studentsClasses.Student student = 2;</code>
   */
  public studentsClasses.StudentOrBuilder getStudentOrBuilder(
      int index) {
    return student_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasProf()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getStudentCount(); i++) {
      if (!getStudent(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, prof_);
    }
    for (int i = 0; i < student_.size(); i++) {
      output.writeMessage(2, student_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, prof_);
    }
    for (int i = 0; i < student_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, student_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof studentsClasses.Classroom)) {
      return super.equals(obj);
    }
    studentsClasses.Classroom other = (studentsClasses.Classroom) obj;

    boolean result = true;
    result = result && (hasProf() == other.hasProf());
    if (hasProf()) {
      result = result && getProf()
          .equals(other.getProf());
    }
    result = result && getStudentList()
        .equals(other.getStudentList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasProf()) {
      hash = (37 * hash) + PROF_FIELD_NUMBER;
      hash = (53 * hash) + getProf().hashCode();
    }
    if (getStudentCount() > 0) {
      hash = (37 * hash) + STUDENT_FIELD_NUMBER;
      hash = (53 * hash) + getStudentList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static studentsClasses.Classroom parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studentsClasses.Classroom parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studentsClasses.Classroom parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studentsClasses.Classroom parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studentsClasses.Classroom parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static studentsClasses.Classroom parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static studentsClasses.Classroom parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static studentsClasses.Classroom parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static studentsClasses.Classroom parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static studentsClasses.Classroom parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(studentsClasses.Classroom prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code studentsClasses.Classroom}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:studentsClasses.Classroom)
      studentsClasses.ClassroomOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return studentsClasses.StudentOuterClass.internal_static_studentsClasses_Classroom_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return studentsClasses.StudentOuterClass.internal_static_studentsClasses_Classroom_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              studentsClasses.Classroom.class, studentsClasses.Classroom.Builder.class);
    }

    // Construct using studentsClasses.Classroom.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStudentFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      prof_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      if (studentBuilder_ == null) {
        student_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        studentBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return studentsClasses.StudentOuterClass.internal_static_studentsClasses_Classroom_descriptor;
    }

    public studentsClasses.Classroom getDefaultInstanceForType() {
      return studentsClasses.Classroom.getDefaultInstance();
    }

    public studentsClasses.Classroom build() {
      studentsClasses.Classroom result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public studentsClasses.Classroom buildPartial() {
      studentsClasses.Classroom result = new studentsClasses.Classroom(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.prof_ = prof_;
      if (studentBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          student_ = java.util.Collections.unmodifiableList(student_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.student_ = student_;
      } else {
        result.student_ = studentBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof studentsClasses.Classroom) {
        return mergeFrom((studentsClasses.Classroom)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(studentsClasses.Classroom other) {
      if (other == studentsClasses.Classroom.getDefaultInstance()) return this;
      if (other.hasProf()) {
        bitField0_ |= 0x00000001;
        prof_ = other.prof_;
        onChanged();
      }
      if (studentBuilder_ == null) {
        if (!other.student_.isEmpty()) {
          if (student_.isEmpty()) {
            student_ = other.student_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureStudentIsMutable();
            student_.addAll(other.student_);
          }
          onChanged();
        }
      } else {
        if (!other.student_.isEmpty()) {
          if (studentBuilder_.isEmpty()) {
            studentBuilder_.dispose();
            studentBuilder_ = null;
            student_ = other.student_;
            bitField0_ = (bitField0_ & ~0x00000002);
            studentBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStudentFieldBuilder() : null;
          } else {
            studentBuilder_.addAllMessages(other.student_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasProf()) {
        return false;
      }
      for (int i = 0; i < getStudentCount(); i++) {
        if (!getStudent(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      studentsClasses.Classroom parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (studentsClasses.Classroom) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object prof_ = "";
    /**
     * <code>required string prof = 1;</code>
     */
    public boolean hasProf() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string prof = 1;</code>
     */
    public java.lang.String getProf() {
      java.lang.Object ref = prof_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          prof_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string prof = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProfBytes() {
      java.lang.Object ref = prof_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prof_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string prof = 1;</code>
     */
    public Builder setProf(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      prof_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string prof = 1;</code>
     */
    public Builder clearProf() {
      bitField0_ = (bitField0_ & ~0x00000001);
      prof_ = getDefaultInstance().getProf();
      onChanged();
      return this;
    }
    /**
     * <code>required string prof = 1;</code>
     */
    public Builder setProfBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      prof_ = value;
      onChanged();
      return this;
    }

    private java.util.List<studentsClasses.Student> student_ =
      java.util.Collections.emptyList();
    private void ensureStudentIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        student_ = new java.util.ArrayList<studentsClasses.Student>(student_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        studentsClasses.Student, studentsClasses.Student.Builder, studentsClasses.StudentOrBuilder> studentBuilder_;

    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public java.util.List<studentsClasses.Student> getStudentList() {
      if (studentBuilder_ == null) {
        return java.util.Collections.unmodifiableList(student_);
      } else {
        return studentBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public int getStudentCount() {
      if (studentBuilder_ == null) {
        return student_.size();
      } else {
        return studentBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public studentsClasses.Student getStudent(int index) {
      if (studentBuilder_ == null) {
        return student_.get(index);
      } else {
        return studentBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public Builder setStudent(
        int index, studentsClasses.Student value) {
      if (studentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentIsMutable();
        student_.set(index, value);
        onChanged();
      } else {
        studentBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public Builder setStudent(
        int index, studentsClasses.Student.Builder builderForValue) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        student_.set(index, builderForValue.build());
        onChanged();
      } else {
        studentBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public Builder addStudent(studentsClasses.Student value) {
      if (studentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentIsMutable();
        student_.add(value);
        onChanged();
      } else {
        studentBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public Builder addStudent(
        int index, studentsClasses.Student value) {
      if (studentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentIsMutable();
        student_.add(index, value);
        onChanged();
      } else {
        studentBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public Builder addStudent(
        studentsClasses.Student.Builder builderForValue) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        student_.add(builderForValue.build());
        onChanged();
      } else {
        studentBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public Builder addStudent(
        int index, studentsClasses.Student.Builder builderForValue) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        student_.add(index, builderForValue.build());
        onChanged();
      } else {
        studentBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public Builder addAllStudent(
        java.lang.Iterable<? extends studentsClasses.Student> values) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, student_);
        onChanged();
      } else {
        studentBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public Builder clearStudent() {
      if (studentBuilder_ == null) {
        student_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        studentBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public Builder removeStudent(int index) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        student_.remove(index);
        onChanged();
      } else {
        studentBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public studentsClasses.Student.Builder getStudentBuilder(
        int index) {
      return getStudentFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public studentsClasses.StudentOrBuilder getStudentOrBuilder(
        int index) {
      if (studentBuilder_ == null) {
        return student_.get(index);  } else {
        return studentBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public java.util.List<? extends studentsClasses.StudentOrBuilder> 
         getStudentOrBuilderList() {
      if (studentBuilder_ != null) {
        return studentBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(student_);
      }
    }
    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public studentsClasses.Student.Builder addStudentBuilder() {
      return getStudentFieldBuilder().addBuilder(
          studentsClasses.Student.getDefaultInstance());
    }
    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public studentsClasses.Student.Builder addStudentBuilder(
        int index) {
      return getStudentFieldBuilder().addBuilder(
          index, studentsClasses.Student.getDefaultInstance());
    }
    /**
     * <code>repeated .studentsClasses.Student student = 2;</code>
     */
    public java.util.List<studentsClasses.Student.Builder> 
         getStudentBuilderList() {
      return getStudentFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        studentsClasses.Student, studentsClasses.Student.Builder, studentsClasses.StudentOrBuilder> 
        getStudentFieldBuilder() {
      if (studentBuilder_ == null) {
        studentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            studentsClasses.Student, studentsClasses.Student.Builder, studentsClasses.StudentOrBuilder>(
                student_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        student_ = null;
      }
      return studentBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:studentsClasses.Classroom)
  }

  // @@protoc_insertion_point(class_scope:studentsClasses.Classroom)
  private static final studentsClasses.Classroom DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new studentsClasses.Classroom();
  }

  public static studentsClasses.Classroom getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Classroom>
      PARSER = new com.google.protobuf.AbstractParser<Classroom>() {
    public Classroom parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Classroom(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Classroom> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Classroom> getParserForType() {
    return PARSER;
  }

  public studentsClasses.Classroom getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

