// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package studentsClasses;

public interface ClassroomOrBuilder extends
    // @@protoc_insertion_point(interface_extends:studentsClasses.Classroom)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string prof = 1;</code>
   */
  boolean hasProf();
  /**
   * <code>required string prof = 1;</code>
   */
  java.lang.String getProf();
  /**
   * <code>required string prof = 1;</code>
   */
  com.google.protobuf.ByteString
      getProfBytes();

  /**
   * <code>repeated .studentsClasses.Student student = 2;</code>
   */
  java.util.List<studentsClasses.Student> 
      getStudentList();
  /**
   * <code>repeated .studentsClasses.Student student = 2;</code>
   */
  studentsClasses.Student getStudent(int index);
  /**
   * <code>repeated .studentsClasses.Student student = 2;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .studentsClasses.Student student = 2;</code>
   */
  java.util.List<? extends studentsClasses.StudentOrBuilder> 
      getStudentOrBuilderList();
  /**
   * <code>repeated .studentsClasses.Student student = 2;</code>
   */
  studentsClasses.StudentOrBuilder getStudentOrBuilder(
      int index);
}
