// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package studentsClasses;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:studentsClasses.Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required int32 id = 2;</code>
   */
  boolean hasId();
  /**
   * <code>required int32 id = 2;</code>
   */
  int getId();
}
