// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package studentsClasses;

public final class StudentOuterClass {
  private StudentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_studentsClasses_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_studentsClasses_Student_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_studentsClasses_Classroom_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_studentsClasses_Classroom_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstudent.proto\022\017studentsClasses\"#\n\007Stud" +
      "ent\022\014\n\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\"D\n\tClassro" +
      "om\022\014\n\004prof\030\001 \002(\t\022)\n\007student\030\002 \003(\0132\030.stud" +
      "entsClasses.StudentB\002P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_studentsClasses_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_studentsClasses_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_studentsClasses_Student_descriptor,
        new java.lang.String[] { "Name", "Id", });
    internal_static_studentsClasses_Classroom_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_studentsClasses_Classroom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_studentsClasses_Classroom_descriptor,
        new java.lang.String[] { "Prof", "Student", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
