// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adressbook.proto

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   */
  String getName();
  /**
   * <code>required string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required int32 id = 2;</code>
   */
  boolean hasId();
  /**
   * <code>required int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>optional string email = 3;</code>
   */
  boolean hasEmail();
  /**
   * <code>optional string email = 3;</code>
   */
  String getEmail();
  /**
   * <code>optional string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated string numbers = 4;</code>
   */
  java.util.List<String>
      getNumbersList();
  /**
   * <code>repeated string numbers = 4;</code>
   */
  int getNumbersCount();
  /**
   * <code>repeated string numbers = 4;</code>
   */
  String getNumbers(int index);
  /**
   * <code>repeated string numbers = 4;</code>
   */
  com.google.protobuf.ByteString
      getNumbersBytes(int index);
}
